name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Build binaries
        run: |
          npm ci
          npm run package

      - name: Prepare distribution
        run: |
          cd dist
          for file in *; do tar -cvzf $file.tar.gz $file; done
          find . -type f -not -name '*.tar.gz' | xargs rm

      - name: Compute checksums
        run: |
          cd dist
          for file in *; do sha256sum $file >> checksums.txt; done

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: outdated-metrics
          path: dist/
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: outdated-metrics
          path: dist/

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
